package com.wxx.unionpay.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wxx.unionpay.entity.ICParams_380;
import com.wxx.unionpay.entity.Public_370;

import com.wxx.unionpay.db.dao.ICParams_380Dao;
import com.wxx.unionpay.db.dao.Public_370Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig iCParams_380DaoConfig;
    private final DaoConfig public_370DaoConfig;

    private final ICParams_380Dao iCParams_380Dao;
    private final Public_370Dao public_370Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        iCParams_380DaoConfig = daoConfigMap.get(ICParams_380Dao.class).clone();
        iCParams_380DaoConfig.initIdentityScope(type);

        public_370DaoConfig = daoConfigMap.get(Public_370Dao.class).clone();
        public_370DaoConfig.initIdentityScope(type);

        iCParams_380Dao = new ICParams_380Dao(iCParams_380DaoConfig, this);
        public_370Dao = new Public_370Dao(public_370DaoConfig, this);

        registerDao(ICParams_380.class, iCParams_380Dao);
        registerDao(Public_370.class, public_370Dao);
    }
    
    public void clear() {
        iCParams_380DaoConfig.clearIdentityScope();
        public_370DaoConfig.clearIdentityScope();
    }

    public ICParams_380Dao getICParams_380Dao() {
        return iCParams_380Dao;
    }

    public Public_370Dao getPublic_370Dao() {
        return public_370Dao;
    }

}
